version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - 443:443
    env_file:
      - .env
    networks:
      - inception_network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception_network
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: volume
      device: /Users/heolee/Desktop/tmp/mariadb
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: volume
      device: /Users/heolee/Desktop/tmp/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge

